# Generated by Django 6.0.1 on 2026-01-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('myapp', '0001_initial'), ('myapp', '0002_professional'), ('myapp', '0003_alter_professional_company_name_and_more'), ('myapp', '0004_delete_item'), ('myapp', '0005_alter_professional_source')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('partner', 'Partner'), ('internal', 'Internal')], db_index=True, default='direct', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
