# Generated by Django 6.0.1 on 2026-01-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_squashed_0005_alter_professional_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='professional',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='email_or_phone_not_null'),
        ),
    ]
